/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role?: string;
  content: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Resource = {
  _id: string;
  _type: "resource";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description?: string;
  type: "pdf" | "link" | "video";
  category: "guides-cliniques" | "recommandations" | "formation";
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  link?: string;
};

export type ArticleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "article";
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  startDate: string;
  endDate?: string;
  location: string;
  description?: BlockContent;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  registrationLink?: string;
  relatedArticle?: ArticleReference;
  recapLink?: string;
  status: "upcoming" | "past" | "cancelled";
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "center" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
>;

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type MemberReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "member";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  author: MemberReference;
  publishedAt: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body: BlockContent;
  categories?: Array<string>;
  seo?: Seo;
};

export type Member = {
  _id: string;
  _type: "member";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName: string;
  lastName: string;
  specialty: string;
  biography?: BlockContent;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  role?:
    | "presidente"
    | "vice-presidente"
    | "tresoriere"
    | "tresoriere-adjointe"
    | "secretaire"
    | "secretaire-adjointe"
    | "membre-bureau";
  email?: string;
  phone?: string;
  linkedin?: string;
};

export type JoinPage = {
  _id: string;
  _type: "joinPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    title: string;
    subtitle?: string;
    cta?: CtaButton;
  };
  modalities?: Array<{
    title: string;
    description: string;
    icon?: IconPicker;
    _key: string;
  }>;
  membershipFee?: {
    amount: number;
    year: number;
  };
  cta?: {
    title?: string;
    body?: string;
    button?: CtaButton;
  };
  seo?: {
    title: string;
    description: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type CtaButton = {
  _type: "ctaButton";
  label: string;
  href: string;
};

export type IconPicker =
  | "heart"
  | "megaphone"
  | "users"
  | "lightbulb"
  | "network"
  | "book-open"
  | "file-text"
  | "trophy"
  | "file-check"
  | "euro"
  | "mail"
  | "briefcase"
  | "target"
  | "user-plus"
  | "award"
  | "star"
  | "graduation-cap"
  | "scale"
  | "calendar"
  | "alert-circle"
  | "presentation"
  | "flask-conical"
  | "facebook"
  | "instagram"
  | "linkedin";

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    title: string;
    subtitle?: string;
  };
  formIntro?: string;
  contactInfoTitle?: string;
  seo?: {
    title: string;
    description: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    title: string;
    subtitle?: string;
  };
  mission?: {
    title: string;
    body?: BlockContent;
  };
  history?: {
    title: string;
    body?: BlockContent;
  };
  values?: Array<{
    title: string;
    description: string;
    icon?: IconPicker;
    _key: string;
  }>;
  keyActions?: Array<{
    title: string;
    description: string;
    icon?: IconPicker;
    _key: string;
  }>;
  seo?: {
    title: string;
    description: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  welcome?: {
    titlePrefix: string;
    titleHighlight: string;
    subtitle?: BlockContent;
  };
  whyFeminine?: {
    title: string;
    items?: Array<{
      title: string;
      text: string;
      icon?: IconPicker;
      _key: string;
    }>;
  };
  whatWeDo?: {
    title: string;
    items?: Array<{
      title: string;
      description?: string;
      icon?: IconPicker;
      _key: string;
    }>;
  };
  callToAction?: {
    title?: string;
    subtitle?: string;
    items?: Array<{
      title: string;
      description?: string;
      icon?: IconPicker;
      buttonLabel: string;
      href: string;
      variant?: "default" | "outline";
      _key: string;
    }>;
  };
  seo?: {
    title: string;
    description: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  associationName: string;
  tagline: string;
  shortMission: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  contactEmails?: Array<{
    label: string;
    email: string;
    description?: string;
    icon?: IconPicker;
    _key: string;
  }>;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  footerColumns?: Array<{
    title: string;
    links?: Array<{
      label: string;
      href: string;
      _key: string;
    }>;
    _key: string;
  }>;
};

export type SocialLink = {
  _type: "socialLink";
  platform: "linkedin" | "twitter" | "instagram" | "facebook" | "youtube";
  url: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Testimonial
  | SanityImageCrop
  | SanityImageHotspot
  | SanityFileAssetReference
  | Resource
  | ArticleReference
  | Event
  | Seo
  | BlockContent
  | Slug
  | MemberReference
  | Article
  | Member
  | JoinPage
  | CtaButton
  | IconPicker
  | ContactPage
  | AboutPage
  | HomePage
  | SiteSettings
  | SocialLink
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: lib/sanity/queries.ts
// Variable: siteSettingsQuery
// Query: *[_id == "siteSettings"][0] {    associationName,    tagline,    shortMission,    "logo": logo {   "url": asset->url,  alt },    contactEmails[] {      label,      email,      description,      icon    },    socialLinks[] {      platform,      url    },    footerColumns[] {      title,      links[] {        label,        href      }    }  }
export type SiteSettingsQueryResult =
  | {
      associationName: null;
      tagline: null;
      shortMission: null;
      logo: null;
      contactEmails: null;
      socialLinks: null;
      footerColumns: null;
    }
  | {
      associationName: string;
      tagline: string;
      shortMission: string;
      logo: {
        url: string | null;
        alt: string;
      } | null;
      contactEmails: Array<{
        label: string;
        email: string;
        description: string | null;
        icon: IconPicker | null;
      }> | null;
      socialLinks: Array<{
        platform: "facebook" | "instagram" | "linkedin" | "twitter" | "youtube";
        url: string;
      }> | null;
      footerColumns: Array<{
        title: string;
        links: Array<{
          label: string;
          href: string;
        }> | null;
      }> | null;
    }
  | null;

// Source: lib/sanity/queries.ts
// Variable: homePageQuery
// Query: *[_id == "homePage"][0] {    welcome {      titlePrefix,      titleHighlight,      subtitle    },    whyFeminine {      title,      items[] { _key, title, text, icon }    },    whatWeDo {      title,      items[] { _key, title, description, icon }    },    callToAction {      title,      subtitle,      items[] { _key, title, description, icon, buttonLabel, href, variant }    },    seo { title, description }  }
export type HomePageQueryResult =
  | {
      welcome: null;
      whyFeminine: null;
      whatWeDo: null;
      callToAction: null;
      seo: null;
    }
  | {
      welcome: null;
      whyFeminine: null;
      whatWeDo: null;
      callToAction: null;
      seo: {
        title: string;
        description: string;
      } | null;
    }
  | {
      welcome: null;
      whyFeminine: null;
      whatWeDo: null;
      callToAction: null;
      seo: {
        title: string | null;
        description: string | null;
      } | null;
    }
  | {
      welcome: {
        titlePrefix: string;
        titleHighlight: string;
        subtitle: BlockContent | null;
      } | null;
      whyFeminine: {
        title: string;
        items: Array<{
          _key: string;
          title: string;
          text: string;
          icon: IconPicker | null;
        }> | null;
      } | null;
      whatWeDo: {
        title: string;
        items: Array<{
          _key: string;
          title: string;
          description: string | null;
          icon: IconPicker | null;
        }> | null;
      } | null;
      callToAction: {
        title: string | null;
        subtitle: string | null;
        items: Array<{
          _key: string;
          title: string;
          description: string | null;
          icon: IconPicker | null;
          buttonLabel: string;
          href: string;
          variant: "default" | "outline" | null;
        }> | null;
      } | null;
      seo: {
        title: string;
        description: string;
      } | null;
    }
  | null;

// Source: lib/sanity/queries.ts
// Variable: contactPageQuery
// Query: *[_id == "contactPage"][0] {    hero { title, subtitle },    formIntro,    contactInfoTitle,    seo { title, description }  }
export type ContactPageQueryResult =
  | {
      hero: null;
      formIntro: null;
      contactInfoTitle: null;
      seo: null;
    }
  | {
      hero: null;
      formIntro: null;
      contactInfoTitle: null;
      seo: {
        title: string;
        description: string;
      } | null;
    }
  | {
      hero: null;
      formIntro: null;
      contactInfoTitle: null;
      seo: {
        title: string | null;
        description: string | null;
      } | null;
    }
  | {
      hero: {
        title: string;
        subtitle: string | null;
      } | null;
      formIntro: null;
      contactInfoTitle: null;
      seo: {
        title: string;
        description: string;
      } | null;
    }
  | {
      hero: {
        title: string;
        subtitle: string | null;
      } | null;
      formIntro: string | null;
      contactInfoTitle: string | null;
      seo: {
        title: string;
        description: string;
      } | null;
    }
  | null;

// Source: lib/sanity/queries.ts
// Variable: joinPageQuery
// Query: *[_id == "joinPage"][0] {    hero { title, subtitle, cta { label, href } },    modalities[] { _key, title, description, icon },    membershipFee { amount, year },    cta { title, body, button { label, href } },    seo { title, description }  }
export type JoinPageQueryResult =
  | {
      hero: null;
      modalities: null;
      membershipFee: null;
      cta: null;
      seo: null;
    }
  | {
      hero: null;
      modalities: null;
      membershipFee: null;
      cta: null;
      seo: {
        title: string;
        description: string;
      } | null;
    }
  | {
      hero: null;
      modalities: null;
      membershipFee: null;
      cta: null;
      seo: {
        title: string | null;
        description: string | null;
      } | null;
    }
  | {
      hero: {
        title: string;
        subtitle: string | null;
        cta: null;
      } | null;
      modalities: null;
      membershipFee: null;
      cta: null;
      seo: {
        title: string;
        description: string;
      } | null;
    }
  | {
      hero: {
        title: string;
        subtitle: string | null;
        cta: {
          label: string;
          href: string;
        } | null;
      } | null;
      modalities: Array<{
        _key: string;
        title: string;
        description: string;
        icon: IconPicker | null;
      }> | null;
      membershipFee: {
        amount: number;
        year: number;
      } | null;
      cta: {
        title: string | null;
        body: string | null;
        button: {
          label: string;
          href: string;
        } | null;
      } | null;
      seo: {
        title: string;
        description: string;
      } | null;
    }
  | null;

// Source: lib/sanity/queries.ts
// Variable: aboutPageQuery
// Query: *[_id == "aboutPage"][0] {    hero { title, subtitle },    mission { title, body },    history { title, body },    values[] { _key, title, description, icon },    keyActions[] { _key, title, description, icon },    seo { title, description }  }
export type AboutPageQueryResult =
  | {
      hero: null;
      mission: null;
      history: null;
      values: null;
      keyActions: null;
      seo: null;
    }
  | {
      hero: null;
      mission: null;
      history: null;
      values: null;
      keyActions: null;
      seo: {
        title: string;
        description: string;
      } | null;
    }
  | {
      hero: null;
      mission: null;
      history: null;
      values: null;
      keyActions: null;
      seo: {
        title: string | null;
        description: string | null;
      } | null;
    }
  | {
      hero: {
        title: string;
        subtitle: string | null;
      } | null;
      mission: null;
      history: null;
      values: null;
      keyActions: null;
      seo: {
        title: string;
        description: string;
      } | null;
    }
  | {
      hero: {
        title: string;
        subtitle: string | null;
      } | null;
      mission: {
        title: string;
        body: BlockContent | null;
      } | null;
      history: {
        title: string;
        body: BlockContent | null;
      } | null;
      values: Array<{
        _key: string;
        title: string;
        description: string;
        icon: IconPicker | null;
      }> | null;
      keyActions: Array<{
        _key: string;
        title: string;
        description: string;
        icon: IconPicker | null;
      }> | null;
      seo: {
        title: string;
        description: string;
      } | null;
    }
  | null;

// Source: lib/sanity/queries.ts
// Variable: articlesListQuery
// Query: *[_type == "article"] | order(publishedAt desc) {    "id": _id,    title,    "slug": slug.current,    "author": author->firstName + " " + author->lastName,    "date": publishedAt,    "image": mainImage {   "url": asset->url,  alt },    categories  }
export type ArticlesListQueryResult = Array<{
  id: string;
  title: string;
  slug: string;
  author: string;
  date: string;
  image: {
    url: string | null;
    alt: string | null;
  } | null;
  categories: Array<string> | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: articleBySlugQuery
// Query: *[_type == "article" && slug.current == $slug][0] {    "id": _id,    title,    "slug": slug.current,    "author": author->firstName + " " + author->lastName,    "date": publishedAt,    "image": mainImage {   "url": asset->url,  alt },    body,    categories,      seo {    title,    description,    image {   "url": asset->url,  alt }  }  }
export type ArticleBySlugQueryResult = {
  id: string;
  title: string;
  slug: string;
  author: string;
  date: string;
  image: {
    url: string | null;
    alt: string | null;
  } | null;
  body: BlockContent;
  categories: Array<string> | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      url: string | null;
      alt: null;
    } | null;
  } | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: eventsListQuery
// Query: *[_type == "event"] | order(startDate desc) {    "id": _id,    title,    "slug": slug.current,    "date": startDate,    endDate,    location,    description,    "image": mainImage {   "url": asset->url,  alt },    registrationLink,    recapLink,    "relatedArticleSlug": relatedArticle->slug.current,    "relatedArticleTitle": relatedArticle->title,    status  }
export type EventsListQueryResult = Array<{
  id: string;
  title: string;
  slug: string;
  date: string;
  endDate: string | null;
  location: string;
  description: BlockContent | null;
  image: {
    url: string | null;
    alt: string | null;
  } | null;
  registrationLink: string | null;
  recapLink: string | null;
  relatedArticleSlug: string | null;
  relatedArticleTitle: string | null;
  status: "cancelled" | "past" | "upcoming";
}>;

// Source: lib/sanity/queries.ts
// Variable: eventBySlugQuery
// Query: *[_type == "event" && slug.current == $slug][0] {    "id": _id,    title,    "slug": slug.current,    "date": startDate,    endDate,    location,    description,    "image": mainImage {   "url": asset->url,  alt },    "gallery": gallery[defined(asset)]{      _key,      "url": asset->url,      alt,      "width": asset->metadata.dimensions.width,      "height": asset->metadata.dimensions.height,      "lqip": asset->metadata.lqip    },    registrationLink,    recapLink,    "relatedArticleSlug": relatedArticle->slug.current,    "relatedArticleTitle": relatedArticle->title,    status,      seo {    title,    description,    image {   "url": asset->url,  alt }  }  }
export type EventBySlugQueryResult = {
  id: string;
  title: string;
  slug: string;
  date: string;
  endDate: string | null;
  location: string;
  description: BlockContent | null;
  image: {
    url: string | null;
    alt: string | null;
  } | null;
  gallery: Array<{
    _key: string;
    url: string;
    alt: string | null;
    width: number | null;
    height: number | null;
    lqip: string | null;
  }> | null;
  registrationLink: string | null;
  recapLink: string | null;
  relatedArticleSlug: string | null;
  relatedArticleTitle: string | null;
  status: "cancelled" | "past" | "upcoming";
  seo: {
    title: string | null;
    description: string | null;
    image: {
      url: string | null;
      alt: null;
    } | null;
  } | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: membersListQuery
// Query: *[_type == "member"] | order(    select(      role == "presidente" => 0,      role == "vice-presidente" => 1,      role == "tresoriere" => 2,      role == "secretaire" => 3,      4    ) asc,    lastName asc  ) {    "id": _id,    firstName,    lastName,    role,    specialty,    biography,    photo {   "url": asset->url,  alt },    email,    phone,    linkedin  }
export type MembersListQueryResult = Array<{
  id: string;
  firstName: string;
  lastName: string;
  role:
    | "membre-bureau"
    | "presidente"
    | "secretaire-adjointe"
    | "secretaire"
    | "tresoriere-adjointe"
    | "tresoriere"
    | "vice-presidente"
    | null;
  specialty: string;
  biography: BlockContent | null;
  photo: {
    url: string | null;
    alt: string | null;
  } | null;
  email: string | null;
  phone: string | null;
  linkedin: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "siteSettings"][0] {\n    associationName,\n    tagline,\n    shortMission,\n    "logo": logo { \n  "url": asset->url,\n  alt\n },\n    contactEmails[] {\n      label,\n      email,\n      description,\n      icon\n    },\n    socialLinks[] {\n      platform,\n      url\n    },\n    footerColumns[] {\n      title,\n      links[] {\n        label,\n        href\n      }\n    }\n  }\n': SiteSettingsQueryResult;
    '\n  *[_id == "homePage"][0] {\n    welcome {\n      titlePrefix,\n      titleHighlight,\n      subtitle\n    },\n    whyFeminine {\n      title,\n      items[] { _key, title, text, icon }\n    },\n    whatWeDo {\n      title,\n      items[] { _key, title, description, icon }\n    },\n    callToAction {\n      title,\n      subtitle,\n      items[] { _key, title, description, icon, buttonLabel, href, variant }\n    },\n    seo { title, description }\n  }\n': HomePageQueryResult;
    '\n  *[_id == "contactPage"][0] {\n    hero { title, subtitle },\n    formIntro,\n    contactInfoTitle,\n    seo { title, description }\n  }\n': ContactPageQueryResult;
    '\n  *[_id == "joinPage"][0] {\n    hero { title, subtitle, cta { label, href } },\n    modalities[] { _key, title, description, icon },\n    membershipFee { amount, year },\n    cta { title, body, button { label, href } },\n    seo { title, description }\n  }\n': JoinPageQueryResult;
    '\n  *[_id == "aboutPage"][0] {\n    hero { title, subtitle },\n    mission { title, body },\n    history { title, body },\n    values[] { _key, title, description, icon },\n    keyActions[] { _key, title, description, icon },\n    seo { title, description }\n  }\n': AboutPageQueryResult;
    '\n  *[_type == "article"] | order(publishedAt desc) {\n    "id": _id,\n    title,\n    "slug": slug.current,\n    "author": author->firstName + " " + author->lastName,\n    "date": publishedAt,\n    "image": mainImage { \n  "url": asset->url,\n  alt\n },\n    categories\n  }\n': ArticlesListQueryResult;
    '\n  *[_type == "article" && slug.current == $slug][0] {\n    "id": _id,\n    title,\n    "slug": slug.current,\n    "author": author->firstName + " " + author->lastName,\n    "date": publishedAt,\n    "image": mainImage { \n  "url": asset->url,\n  alt\n },\n    body,\n    categories,\n    \n  seo {\n    title,\n    description,\n    image { \n  "url": asset->url,\n  alt\n }\n  }\n\n  }\n': ArticleBySlugQueryResult;
    '\n  *[_type == "event"] | order(startDate desc) {\n    "id": _id,\n    title,\n    "slug": slug.current,\n    "date": startDate,\n    endDate,\n    location,\n    description,\n    "image": mainImage { \n  "url": asset->url,\n  alt\n },\n    registrationLink,\n    recapLink,\n    "relatedArticleSlug": relatedArticle->slug.current,\n    "relatedArticleTitle": relatedArticle->title,\n    status\n  }\n': EventsListQueryResult;
    '\n  *[_type == "event" && slug.current == $slug][0] {\n    "id": _id,\n    title,\n    "slug": slug.current,\n    "date": startDate,\n    endDate,\n    location,\n    description,\n    "image": mainImage { \n  "url": asset->url,\n  alt\n },\n    "gallery": gallery[defined(asset)]{\n      _key,\n      "url": asset->url,\n      alt,\n      "width": asset->metadata.dimensions.width,\n      "height": asset->metadata.dimensions.height,\n      "lqip": asset->metadata.lqip\n    },\n    registrationLink,\n    recapLink,\n    "relatedArticleSlug": relatedArticle->slug.current,\n    "relatedArticleTitle": relatedArticle->title,\n    status,\n    \n  seo {\n    title,\n    description,\n    image { \n  "url": asset->url,\n  alt\n }\n  }\n\n  }\n': EventBySlugQueryResult;
    '\n  *[_type == "member"] | order(\n    select(\n      role == "presidente" => 0,\n      role == "vice-presidente" => 1,\n      role == "tresoriere" => 2,\n      role == "secretaire" => 3,\n      4\n    ) asc,\n    lastName asc\n  ) {\n    "id": _id,\n    firstName,\n    lastName,\n    role,\n    specialty,\n    biography,\n    photo { \n  "url": asset->url,\n  alt\n },\n    email,\n    phone,\n    linkedin\n  }\n': MembersListQueryResult;
  }
}
